config:
  feeds:
    - https://umutaki.com/feed
  prompt:
    system-prompt: |
      You are blog writer and you want to write a new article.
    user-prompt: |
      Write an article about "{{.Title}}"
      Use markdown to format your article.
      For SEO purposes, please use headings and bold text.
      {{if .Content}}
      Example Content:
      {{.Content}}
      {{else if .Description}}
      Example Description:
      {{.Description}}
      {{end}}